### ISSUE TITLE
topic wildcards not woking

### ISSUE THREAD

**Issue by quantenschaum** [wutu/pimatic-mqtt#11]
If I subscribe to topics using wildcards, it does not work. The device is not updated. Is this intentionally like that?

**Comment by wutu** [comment]
I have not tested this. Today I'll look into it.

**Comment by wutu** [comment]
Hey @quantenschaum 
I did some research around that. I will add some MQTT msg router. It is linked to the task of supporting multiple brokers.
It will require some time, I'm working on it.

**Comment by mwittig** [comment]
released pimatic-mqtt@0.9.13
