### ISSUE TITLE
Aeon Multisensor - Motion + Tempreture

### ISSUE THREAD

**Issue by hongkongkiwi** [wutu/pimatic-mqtt#12]
Hi there,

Thanks a lot for such a great project, I'm currently using this with smartthings-mqtt-bridge to get all my smartthings data into pimatic.

Currently I'm using the Aeon Multisensor, which has tempereture, humdity, illumiance, battery and motion.

Is it possible to combine these together into one "device"? Currently I can do everything except motion and then the motion is a different device.

**Comment by wutu** [comment]
Thx. Glad to hear it.
Yes you're right. Into one device that can not be merged.
