### ISSUE TITLE
Options parameter in mqtt_action

### ISSUE THREAD

**Issue by saxn-paule** [wutu/pimatic-mqtt#13]
Could you please add a possibility to add an options object to a rule

like
`
if blah then publish mqtt message "cool message" on topic "cool/topic" with options "\{\"retain\":true\}"
`

**Comment by wutu** [comment]
Hi, sure, I'll look at it.

**Comment by saxn-paule** [comment]
Thank you very much.

**Comment by wutu** [comment]
ccbcd75eff867828979d60d86b2a5b14ddd277c2
