### ISSUE TITLE
accessing attributes yields entire JSON

### ISSUE THREAD

**Issue by quantenschaum** [wutu/pimatic-mqtt#16]
I configured a device like 

```
{
   "class": "MqttSensor",
      "id": "location",
      "name": "location",
      "attributes": [
        {
          "name": "lat",
          "topic": "owntracks/xy/device",
          "type": "number",
          "unit": "°",
          "acronym": "latitude"
        },
        {
          "name": "lon",
          "topic": "owntracks/xy/device",
          "type": "number",
          "unit": "°",
          "acronym": "longitude"
        }
      ]
}
```

In the UI the device shows up correctly and lat and lon are shown as separate values. The graphs are displayed correctly and the devices' attributes show up in the variables view, too.

But when I want to access the attributes of the device like `$location.lat` in a rule or variable expression, it does not yield the expected value, but the entire mqtt message payload, the raw JSON.

**Comment by wutu** [comment]
Hey, thanks for your report. Looking at it as soon as possible.

**Comment by wutu** [comment]
https://github.com/wutu/pimatic-mqtt/commit/9d4103da79675ec032999280005b23602915b84b
