### ISSUE TITLE
 A uncaught exception occured: TypeError: Cannot read property 'forEach' 

### ISSUE THREAD

**Issue by hyp3rx** [wutu/pimatic-mqtt#18]
After Yesterdays update pimatic crashes instantly ! I had to deactivate the plugin.
delete and reinstalled does´nt help here !:

11:33:20.520 [pimatic] error: A uncaught exception occured: TypeError: Cannot read property 'forEach' of undefined
11:33:20.520 [pimatic] error:>    at outgoing.(anonymous function) (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:465:11)
11:33:20.520 [pimatic] error:>    at that.outgoing.(anonymous function) (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:140:15)
11:33:20.520 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:881:9
11:33:20.520 [pimatic] error:>    at Store.del (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/store.js:77:5)
11:33:20.520 [pimatic] error:>    at MqttClient._handleAck (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:868:26)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:293:12)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
11:33:20.520 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
11:33:20.520 [pimatic] error:>    at Writable.writable._write (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:252:5)
11:33:20.520 [pimatic] error:>    at doWrite (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:319:64)
11:33:20.520 [pimatic] error:>    at writeOrBuffer (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:308:5)
11:33:20.520 [pimatic] error:>    at Writable.write (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:246:11)
11:33:20.520 [pimatic] error:>    at Socket.ondata (_stream_readable.js:542:20)
11:33:20.520 [pimatic] error:>    at emitOne (events.js:77:13)
11:33:20.520 [pimatic] error:>    at Socket.emit (events.js:169:7)
11:33:20.520 [pimatic] error:>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
11:33:20.520 [pimatic] error:>    at readableAddChunk (_stream_readable.js:153:18)
11:33:20.520 [pimatic] error:>    at Socket.Readable.push (_stream_readable.js:111:10)
11:33:20.520 [pimatic] error:>    at TCP.onread (net.js:536:20)
11:33:20.520 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
11:33:20.527 [pimatic] info: exiting...

**Comment by wutu** [comment]
Please send configuration of MQTT plugin.

**Comment by hyp3rx** [comment]
```
{
  "plugin": "mqtt",
  "active": true,
  "brokers": [
    {
      "host": "127.0.0.1",
      "port": 1883,
      "protocolId": "MQTT",
      "reconnect": 5000,
      "brokerId": "default"
    }
  ]
},
```

**Comment by hyp3rx** [comment]
What now? I have currently dissabled the Plugin...

**Comment by wutu** [comment]
Update to 0.9.3. Your plugin config is ok. This looks like an error in the configuration of a device that uses subscribe.
If the error persists, send devices config.

**Comment by hyp3rx** [comment]
Everything is working now with 0.9.3 thank you
