### ISSUE TITLE
MQTT Buttons - Incoming Message Issue

### ISSUE THREAD

**Issue by aap82** [wutu/pimatic-mqtt#19]
I believe the logic for how to handle incoming messages is incorrect:

>       for b in @config.buttons
>         if b.stateTopic
>           @mqttclient.on 'message', (topic, message) =>
>             if b.stateTopic == topic
>               payload = message.toString()
>             if payload == b.message
>               @emit 'button', b.id
> 

As its written above, you add an on message handler for n buttons in the button device, and emits n updates for a state update of a single button.

**Comment by wutu** [comment]
Thx for reporting. Fixed in https://github.com/wutu/pimatic-mqtt/commit/5f8988b4617581a672d9a5fbcbed730558b31eff

**Comment by aap82** [comment]
no problem.
