### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hyp3rx** [wutu/pimatic-mqtt#20]
I have several crashes on Pimatic start sometimes:

08:52:50.533 [pimatic-mqtt] info: Successfully connected to MQTT Broker default
08:52:53.402 [pimatic] error: A uncaught exception occured: TypeError: Cannot read property 'forEach' of undefined
08:52:53.402 [pimatic] error:>    at outgoing.(anonymous function) (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:465:11)
08:52:53.402 [pimatic] error:>    at that.outgoing.(anonymous function) (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:140:15)
08:52:53.402 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:881:9
08:52:53.402 [pimatic] error:>    at Store.del (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/store.js:77:5)
08:52:53.402 [pimatic] error:>    at MqttClient._handleAck (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:868:26)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:293:12)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
08:52:53.402 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
08:52:53.402 [pimatic] error:>    at Writable.writable._write (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:252:5)
08:52:53.402 [pimatic] error:>    at doWrite (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:319:64)
08:52:53.402 [pimatic] error:>    at writeOrBuffer (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:308:5)
08:52:53.402 [pimatic] error:>    at Writable.write (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:246:11)
08:52:53.402 [pimatic] error:>    at Socket.ondata (_stream_readable.js:542:20)
08:52:53.402 [pimatic] error:>    at emitOne (events.js:77:13)
08:52:53.402 [pimatic] error:>    at Socket.emit (events.js:169:7)
08:52:53.402 [pimatic] error:>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
08:52:53.402 [pimatic] error:>    at readableAddChunk (_stream_readable.js:153:18)
08:52:53.402 [pimatic] error:>    at Socket.Readable.push (_stream_readable.js:111:10)
08:52:53.402 [pimatic] error:>    at TCP.onread (net.js:536:20)
08:52:53.402 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
08:52:53.409 [pimatic] info: exiting...

**Comment by hyp3rx** [comment]
Rebooting will result that for the first time, everything works again. But if i restart pimatic, then the problem is back again

**Comment by wutu** [comment]
https://github.com/wutu/pimatic-mqtt/issues/18

**Comment by wutu** [comment]
Send plugin config pls.

**Comment by hyp3rx** [comment]
```
  "brokers": [
    {
      "brokerId": "default",
      "host": "127.0.0.1",
      "port": 1883,
      "keepalive": 180,
      "protocolId": "MQTT",
      "reconnect": 5000
    }
  ],
  "plugin": "mqtt",
  "active": true
}
```

**Comment by wutu** [comment]
Config is fine. I can not reproduce the bug. Looks like some kind of a problem subscribing in of a device (sensor?).

**Comment by wutu** [comment]
Problem still occurs?
