### ISSUE TITLE
Can't send json string

### ISSUE THREAD

**Issue by ManuelW77** [wutu/pimatic-mqtt#22]
hey there,

it wont work to send some json string with a rule.
I try'd this

"rule": "when every 15 seconds then publish mqtt message \"{\"cpu\":$plex-systeminfo.cpu,\"memory\":$plex-systeminfo.memory}\" on topic \"pimaticAZ/system\""

and this

"rule": "when every 15 seconds then publish mqtt message \"{cpu:$plex-systeminfo.cpu,memory:$plex-systeminfo.memory}\" on topic \"pimaticAZ/system\""

and some other constalations, but i can't get it work to send a json string.

Can you help me with this?

**Comment by ManuelW77** [comment]
Hmpf, i get it work, got a light on my head when i send this. 

"rule": "when every 15 seconds then publish mqtt message \"\{\"cpu\":$plex-systeminfo.cpu,\"memory\":$plex-systeminfo.memory\}\" on topic \"pimaticAZ/system\""

**Comment by wutu** [comment]
Hey,
it is necessary to escape quotes and angle brackets.
For example:

`publish mqtt message "\{\"series\":20\}" on topic "/outbox/pimatic/RootDisk"`
