### ISSUE TITLE
Annotation of numbers

### ISSUE THREAD

**Issue by WasVerzachter** [wutu/pimatic-mqtt#24]
Hi,

I'm using the pimatic-mqtt plugin for a while. It's working very stable, thanks for that.
However I do have a question/request for change.
I use multiple temperature sensors in combination with several ESP Easy devices; I have configured it to send the temperatures to the mosquito server on one decimal accurate (eg. 23.3 or 25.9 degrees Celcius).
All is working wel, however within Pimatic, the value 24 is displayed instead of 24.0 (is for all values with the decimal value .0). Is there a possibility to get it displayed with the .0?
Regards and thanks in advance for your reply,
Was

**Comment by wutu** [comment]
Hi, this is the property of Pimatic itself.
