### ISSUE TITLE
Message Map

### ISSUE THREAD

**Issue by timpur** [wutu/pimatic-mqtt#25]
Is it possible to use message maps for converting string to numbers. 
example i want to convert "true" to 1 and still be able to use the type "number" thus these values can be logged in pimatic db and graphed ?

this would be useful in a lot of other situations :)

Tim.

**Comment by wutu** [comment]
Hi Tim. Now it is possible.
https://github.com/wutu/pimatic-mqtt/commit/9d1c95fce144aca080cb053bd50b84ca228a779b

**Comment by timpur** [comment]
:). Thanks
