### ISSUE TITLE
Add MQTT shutter

### ISSUE THREAD

**Issue by sandervandegeijn** [wutu/pimatic-mqtt#28]
I'm installing nodemcu's with espeasy to control all my shutters in the house (and the garage door). I'm missing a mqtt shutter (with state) as a plugin. This would be helpful, now I'm using a dummy shutter with a batch of rules to get it done, but this kind of sucks..

**Comment by wutu** [comment]
7596d7c

**Comment by sandervandegeijn** [comment]
Dude you're awesome!
