### ISSUE TITLE
Multiplier/division not working for mqtt-sensor

### ISSUE THREAD

**Issue by sandervandegeijn** [wutu/pimatic-mqtt#32]
![image](https://user-images.githubusercontent.com/2643715/33795233-ed8c2a62-dcdd-11e7-904d-9f996bdbe5f9.png)

![image](https://user-images.githubusercontent.com/2643715/33795236-01d4d6f4-dcde-11e7-8ed8-90b5a38beb94.png)

still outputs the value received from mqtt instead of calculated value in frontend

![image](https://user-images.githubusercontent.com/2643715/33795245-20506dfa-dcde-11e7-8fb6-86678c5b8122.png)

Using mqtt 0.9.9

**Comment by mwittig** [comment]
I have tested the case with pimatic-mqtt@0.9.11 where it works fine as expected. I am closing this topic now. Should you still experience problems please re-open the ticket eventually
