### ISSUE TITLE
JSON Parsing for switchstate topic

### ISSUE THREAD

**Issue by maffmeier** [wutu/pimatic-mqtt#34]
Hey,

in my setup i have a knx2mqtt bridge.
It translates the State telegram to a json message. It would be nice if there is a way to parse a specific json attribute for switchstate.

- maffmeier

**Comment by georg90** [comment]
Same for zigbee2mqtt switches.

They publish a message like `MQTT publish: topic 'zigbee2mqtt/WD NAS OSRAM Plug', payload '{"state":"ON","linkquality":34}'`

**Comment by mwittig** [comment]
released pimatic-mqtt@0.9.13
