### ISSUE TITLE
Getting error 'Cannot call method 'then' of undefined' when using the MqttSwitch in a rule.

### ISSUE THREAD

**Issue by rovale** [wutu/pimatic-mqtt#4]
I am pretty sure it is related to https://github.com/MMore/pimatic-z-way/pull/2/files. If it helps I can make a pull request to fix it, too.

BTW, thanks a lot for this great plug in.

**Comment by wutu** [comment]
Thanks for the info. Fixed in the new version 0.8.6.

**Comment by rovale** [comment]
Great, thanks a lot and keep up the good work!
