### ISSUE TITLE
Feature request: auto detect

### ISSUE THREAD

**Issue by flatsiedatsie** [wutu/pimatic-mqtt#42]
Would it be possible that the plugin auto-detects new MQTT devices and shows them in the new devices list?

**Comment by mwittig** [comment]
Generally, that's possible as one can use wildcards on subscription topics. In other words it is possible  to subscribe all topics out there. However, mqtt do not contain a lot of meta.data identify the type of publishing device. Just from the payload data received it is not clear to which type of device they belong to and what topic is required to publish data in case of an actor. 

In my opinion, a generic auto-detection does not make much sense here.  However, there may be use-cases where implicit knowledge can be used to guess which type of device has published the data. For example, as many users use the tasmota firmware for their devices, one could build a tasmota-specific device auto-detection using knowledge derived from tasmota device templates. 

I am closing this now. Please feel free to re-open if you want to follow-up on this. If you want to create feature request please use the pimatic forum. https://forum.pimatic.org/category/14/feature-requests
