### ISSUE TITLE
Add MqttTemperatureSensor

### ISSUE THREAD

**Issue by michbeck100** [wutu/pimatic-mqtt#7]
It would be great if there was a specific Device Class for a TemperatureSensor.

**Comment by wutu** [comment]
For a long time I thought about it. I just do not see any reason why separated temperature as special device. From the perspective MQTT, it is value as any other.
There is really no other way?

**Comment by michbeck100** [comment]
But why are there special classes for switches, presence sensors etc? From the MQTT perspective you are right, thats irrelevant, but from the pimatic perspective it's not. Not just because of the piamtic-hap plugin but also for special ui elements and the device's api.

**Comment by wutu** [comment]
For special ui elements I was ready to introduce some way of tagging values (I wish example, the corresponding icon in Pimatic). But it would be well taken globally, for all modules.
As said Andy Stanford-Clark:
"Just like the postal service, MQTT doesn't care what you send."
So I am saying no for now.

https://forum.pimatic.org/topic/1773/some-kind-of-marking-by-the-type-attribute
